<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'status' => 'active',
                'type' => 'Elektronik',
                'category' => 'Telefon',
                'brand' => 'Apple',
                'product_code' => 'IP13-128',
                'name' => 'iPhone 13 128GB',
                'name_en' => 'iPhone 13 128GB',
                'unit' => 'adet',
                'vat_rate' => 18,
                'box_content' => 'iPhone 13, Şarj Kablosu, Kulaklık',
                'order' => 1,
                'desi' => 0.5,
                'points' => 100,
                'barcode' => '123456789',
                'price1' => 39999.99,
                'price2' => 38999.99,
                'price3' => 37999.99,
                'price4' => 36999.99,
                'price5' => 35999.99,
                'currency1' => 'TRY',
                'currency2' => 'TRY',
                'currency3' => 'TRY',
                'currency4' => 'TRY',
                'currency5' => 'TRY',
                'discounted_price' => 34999.99,
                'discounted_currency' => 'TRY',
                'cost' => 30000.00,
                'discount_rate' => 12.5,
                'additional_discount' => 5,
                'discount_group_code' => 'IP13',
                'min_order' => 1,
                'increment' => 1,
                'max_order' => 10,
                'warehouse1_stock' => 50,
                'warehouse2_stock' => 30,
                'warehouse3_stock' => 20,
                'photo' => 'iphone13.jpg',
                'description' => 'iPhone 13 128GB Akıllı Telefon',
                'description_en' => 'iPhone 13 128GB Smartphone',
                'search_tags' => 'iphone,apple,telefon,akıllı telefon',
                'counter_date' => null,
                'discount_stock_date' => null,
                'is_passive' => false,
                'is_closed' => false,
                'is_out_of_stock' => false,
                'is_showcase' => true,
                'is_bestseller' => true,
                'is_campaign' => false,
                'has_gift' => false,
                'is_new' => true,
                'has_counter' => false,
                'has_discount_stock' => false,
            ],
            [
                'status' => 'active',
                'type' => 'Elektronik',
                'category' => 'Bilgisayar',
                'brand' => 'Apple',
                'product_code' => 'MBA-M1',
                'name' => 'MacBook Air M1',
                'name_en' => 'MacBook Air M1',
                'unit' => 'adet',
                'vat_rate' => 18,
                'box_content' => 'MacBook Air, Şarj Kablosu',
                'order' => 2,
                'desi' => 1.2,
                'points' => 200,
                'barcode' => '987654321',
                'price1' => 49999.99,
                'price2' => 48999.99,
                'price3' => 47999.99,
                'price4' => 46999.99,
                'price5' => 45999.99,
                'currency1' => 'TRY',
                'currency2' => 'TRY',
                'currency3' => 'TRY',
                'currency4' => 'TRY',
                'currency5' => 'TRY',
                'discounted_price' => 44999.99,
                'discounted_currency' => 'TRY',
                'cost' => 40000.00,
                'discount_rate' => 10,
                'additional_discount' => 0,
                'discount_group_code' => 'MBA',
                'min_order' => 1,
                'increment' => 1,
                'max_order' => 5,
                'warehouse1_stock' => 30,
                'warehouse2_stock' => 20,
                'warehouse3_stock' => 10,
                'photo' => 'macbook-air.jpg',
                'description' => 'MacBook Air M1 Laptop',
                'description_en' => 'MacBook Air M1 Laptop',
                'search_tags' => 'macbook,apple,laptop,bilgisayar',
                'counter_date' => null,
                'discount_stock_date' => null,
                'is_passive' => false,
                'is_closed' => false,
                'is_out_of_stock' => false,
                'is_showcase' => true,
                'is_bestseller' => true,
                'is_campaign' => false,
                'has_gift' => false,
                'is_new' => false,
                'has_counter' => false,
                'has_discount_stock' => false,
            ],
            [
                'status' => 'active',
                'type' => 'Elektronik',
                'category' => 'Tablet',
                'brand' => 'Apple',
                'product_code' => 'IPAD-2021',
                'name' => 'iPad 2021',
                'name_en' => 'iPad 2021',
                'unit' => 'adet',
                'vat_rate' => 18,
                'box_content' => 'iPad, Şarj Kablosu',
                'order' => 3,
                'desi' => 0.8,
                'points' => 150,
                'barcode' => '456789123',
                'price1' => 29999.99,
                'price2' => 28999.99,
                'price3' => 27999.99,
                'price4' => 26999.99,
                'price5' => 25999.99,
                'currency1' => 'TRY',
                'currency2' => 'TRY',
                'currency3' => 'TRY',
                'currency4' => 'TRY',
                'currency5' => 'TRY',
                'discounted_price' => 24999.99,
                'discounted_currency' => 'TRY',
                'cost' => 20000.00,
                'discount_rate' => 16.67,
                'additional_discount' => 0,
                'discount_group_code' => 'IPAD',
                'min_order' => 1,
                'increment' => 1,
                'max_order' => 8,
                'warehouse1_stock' => 40,
                'warehouse2_stock' => 25,
                'warehouse3_stock' => 15,
                'photo' => 'ipad-2021.jpg',
                'description' => 'iPad 2021 Tablet',
                'description_en' => 'iPad 2021 Tablet',
                'search_tags' => 'ipad,apple,tablet',
                'counter_date' => null,
                'discount_stock_date' => null,
                'is_passive' => false,
                'is_closed' => false,
                'is_out_of_stock' => false,
                'is_showcase' => true,
                'is_bestseller' => false,
                'is_campaign' => false,
                'has_gift' => false,
                'is_new' => false,
                'has_counter' => false,
                'has_discount_stock' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
